version: '3.1'
services:
  app:
    container_name: spring-k8s
    image: giatien310/spring-k8s
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgresqldb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fruitdb