kind: Service
apiVersion: v1
metadata:
  name: spring-k8s
  labels:
    name: spring-k8s
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-k8s
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s
spec:
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
        - name: spring-k8s
          image: giatien310/spring-k8s:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: POSTGRES_DB  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: POSTGRES_DB
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf # Secret Name
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: POSTGRES_PASSWORD